define(['jquery','util','issues'],function($,u,issues){
  return{
  	scheme:[],/*方案内容*/
    tmpBet:{/*缓存当前号码*/},
    tmpU:0,/*选号注数*/
    u:0,/*确认注数*/
    setPlay:function(o){/*初始化玩法*/
      this.play[o].choose();
      this.tmpBet={};/*清除当前号码缓存*/
      this.setTmpBet=this.play[o].setTmpBet;/*重写临时号码缓存格式方法*/
      this.setTmpBet();/*设置临时号码缓存格式*/
      this.count=this.play[o].count;/*重写注数计算方法*/
      this.selected=this.play[o].selected;/*重写点击事件*/
      this.playName=this.play[o].playName;/*重写玩法名称*/
      this.inputName=this.play[o].inputName;/*重写玩法提交名称*/
      this.random=this.play[o].random;/*重写机选方法*/
      this.addContent=this.play[o].addContent;/*重写添加方法*/
      this.tmpU=0;
      this.setTmpU();
    },
    setTmpU:function(){
    	$("#curBets").html(this.tmpU);
      $("#curMoney").html(this.tmpU*2);
    },
    clear:function(){
      $('.rb').removeClass('rb');
      this.setTmpBet();
      this.tmpU=0;
      this.setTmpU();
    },
    add:function(){
      if(this.tmpU==0){
      	var that=this;
        u.confirm('您选择的方案不构成注,机选一注么？',function(){
          that.random();
          that.addContent();
          that.clear();
        });
      }else{
        this.addContent();
        this.clear();
      }
    },
    calc:function(){/*计算注数*/
      var i= 0,len=this.scheme.length,u=0;
      for(i;i<len;i++){
        u+=this.scheme[i].u;
      }
      this.u=u;
      this.showMoney();
    },
    mul:1,
    muls:[],
    issueIds:[],
    totalIssueIds:[],
    showMoney:function(){
      $("#Bets").html(this.u);
      $("#singleBetMoney").html(this.u*2);
      $("#Money").html(this.u*this.mul*this.issueIds.length*2);
    },
    submit:function(){
      var i= 0,D=this.scheme,scheme={},schemeNumber=[],d;
      for(i;i< D.length;i++){
        if(scheme[D[i].inputName]==undefined){
          scheme[D[i].inputName]=[];
        }
        scheme[D[i].inputName].push(D[i].bet);
      }
      i=0;
      for(i in scheme){
        schemeNumber.push(i+"="+scheme[i].join("|"));
      }
      d={
        schemeNumber:schemeNumber.join(';'),
        multiple:this.mul,
        multiples:this.muls,
        money:this.u*this.mul*2,
        issueId:window.issueIds[0],
        issueIds:window.issueIds
      }
      console.log(d);
    }
  };
});